require "test_helper"

class TachyonManifold::TotalTimelinesTest < Minitest::Test
  def setup
    @manifold = TachyonManifold.new beam: "|", empty: ".", splitter: "^", start: "S"
  end

  def test_aoc_example
    input = ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"
    @manifold.diagram = input.each_line.map(&:chomp)

    assert_equal 40, @manifold.total_timelines
  end
end
